"""Add GTFS feed architecture

Revision ID: dbca6c010ccf
Revises: 37f0f0fd6361
Create Date: 2025-11-22 04:15:32.645536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'dbca6c010ccf'
down_revision: Union[str, None] = '37f0f0fd6361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop old GTFS tables from 001_initial_schema if they exist
    # These had a different schema (agency_id instead of feed_id)
    # Also drop any existing indexes that might conflict
    op.execute("DROP INDEX IF EXISTS idx_gtfs_shapes_geom")
    op.execute("DROP INDEX IF EXISTS idx_gtfs_stops_geom")
    op.execute("DROP TABLE IF EXISTS gtfs_stop_times CASCADE")
    op.execute("DROP TABLE IF EXISTS gtfs_trips CASCADE")
    op.execute("DROP TABLE IF EXISTS gtfs_calendar_dates CASCADE")
    op.execute("DROP TABLE IF EXISTS gtfs_calendar CASCADE")
    op.execute("DROP TABLE IF EXISTS gtfs_routes CASCADE")
    op.execute("DROP TABLE IF EXISTS gtfs_stops CASCADE")
    op.execute("DROP TABLE IF EXISTS gtfs_shapes CASCADE")
    op.execute("DROP TABLE IF EXISTS gtfs_agencies CASCADE")

    op.create_table('gtfs_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Descriptive name for this feed'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True, comment='Optional version identifier'),
    sa.Column('imported_at', sa.String(length=30), nullable=False, comment='ISO timestamp of import'),
    sa.Column('imported_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this feed is currently active'),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('total_routes', sa.Integer(), nullable=True),
    sa.Column('total_stops', sa.Integer(), nullable=True),
    sa.Column('total_trips', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_feeds_agency_id'), 'gtfs_feeds', ['agency_id'], unique=False)
    op.create_index(op.f('ix_gtfs_feeds_id'), 'gtfs_feeds', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_feeds_imported_by'), 'gtfs_feeds', ['imported_by'], unique=False)
    op.create_table('gtfs_agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('gtfs_agency_id', sa.String(length=255), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=False),
    sa.Column('agency_url', sa.String(length=500), nullable=False),
    sa.Column('agency_timezone', sa.String(length=100), nullable=False),
    sa.Column('agency_lang', sa.String(length=10), nullable=True),
    sa.Column('agency_phone', sa.String(length=50), nullable=True),
    sa.Column('agency_fare_url', sa.String(length=500), nullable=True),
    sa.Column('agency_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_agencies_feed_id'), 'gtfs_agencies', ['feed_id'], unique=False)
    op.create_index(op.f('ix_gtfs_agencies_id'), 'gtfs_agencies', ['id'], unique=False)
    op.create_table('gtfs_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.String(length=8), nullable=False, comment='YYYYMMDD'),
    sa.Column('end_date', sa.String(length=8), nullable=False, comment='YYYYMMDD'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_calendar_feed_id'), 'gtfs_calendar', ['feed_id'], unique=False)
    op.create_index(op.f('ix_gtfs_calendar_id'), 'gtfs_calendar', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_calendar_service_id'), 'gtfs_calendar', ['service_id'], unique=False)
    op.create_table('gtfs_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=255), nullable=False),
    sa.Column('gtfs_agency_id', sa.String(length=255), nullable=True),
    sa.Column('route_short_name', sa.String(length=50), nullable=False),
    sa.Column('route_long_name', sa.String(length=255), nullable=False),
    sa.Column('route_desc', sa.Text(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=False, comment='0=Tram, 1=Subway, 2=Rail, 3=Bus, 4=Ferry, 5=Cable car, 6=Gondola, 7=Funicular'),
    sa.Column('route_url', sa.String(length=500), nullable=True),
    sa.Column('route_color', sa.String(length=6), nullable=True),
    sa.Column('route_text_color', sa.String(length=6), nullable=True),
    sa.Column('route_sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_routes_feed_id'), 'gtfs_routes', ['feed_id'], unique=False)
    op.create_index(op.f('ix_gtfs_routes_id'), 'gtfs_routes', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_routes_route_id'), 'gtfs_routes', ['route_id'], unique=False)
    op.create_index(op.f('ix_gtfs_routes_route_short_name'), 'gtfs_routes', ['route_short_name'], unique=False)
    op.create_table('gtfs_shapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('shape_id', sa.String(length=255), nullable=False),
    sa.Column('shape_pt_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('shape_pt_lon', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('shape_pt_sequence', sa.Integer(), nullable=False),
    sa.Column('shape_dist_traveled', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='PostGIS geometry'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_gtfs_shapes_geom ON gtfs_shapes USING gist (geom)")
    op.create_index(op.f('ix_gtfs_shapes_feed_id'), 'gtfs_shapes', ['feed_id'], unique=False)
    op.create_index(op.f('ix_gtfs_shapes_id'), 'gtfs_shapes', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_shapes_shape_id'), 'gtfs_shapes', ['shape_id'], unique=False)
    op.create_table('gtfs_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(length=255), nullable=False),
    sa.Column('stop_code', sa.String(length=50), nullable=True),
    sa.Column('stop_name', sa.String(length=255), nullable=False),
    sa.Column('stop_desc', sa.Text(), nullable=True),
    sa.Column('stop_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('stop_lon', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('zone_id', sa.String(length=50), nullable=True),
    sa.Column('stop_url', sa.String(length=500), nullable=True),
    sa.Column('location_type', sa.Integer(), nullable=True, comment='0=stop, 1=station, 2=entrance, 3=node'),
    sa.Column('parent_station', sa.String(length=255), nullable=True),
    sa.Column('stop_timezone', sa.String(length=100), nullable=True),
    sa.Column('wheelchair_boarding', sa.Integer(), nullable=True, comment='0=no info, 1=accessible, 2=not accessible'),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='PostGIS geometry point'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_gtfs_stops_geom ON gtfs_stops USING gist (geom)")
    op.create_index(op.f('ix_gtfs_stops_feed_id'), 'gtfs_stops', ['feed_id'], unique=False)
    op.create_index(op.f('ix_gtfs_stops_id'), 'gtfs_stops', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_stops_stop_id'), 'gtfs_stops', ['stop_id'], unique=False)
    op.create_index(op.f('ix_gtfs_stops_stop_name'), 'gtfs_stops', ['stop_name'], unique=False)
    op.create_table('gtfs_calendar_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=False, comment='YYYYMMDD'),
    sa.Column('exception_type', sa.Integer(), nullable=False, comment='1=service added, 2=service removed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['gtfs_calendar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_calendar_dates_id'), 'gtfs_calendar_dates', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_calendar_dates_service_id'), 'gtfs_calendar_dates', ['service_id'], unique=False)
    op.create_table('gtfs_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=255), nullable=False),
    sa.Column('trip_headsign', sa.String(length=255), nullable=True),
    sa.Column('trip_short_name', sa.String(length=50), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True, comment='0=outbound, 1=inbound'),
    sa.Column('block_id', sa.String(length=50), nullable=True),
    sa.Column('shape_id', sa.Integer(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Integer(), nullable=True, comment='0=no info, 1=accessible, 2=not accessible'),
    sa.Column('bikes_allowed', sa.Integer(), nullable=True, comment='0=no info, 1=allowed, 2=not allowed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['gtfs_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['gtfs_calendar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shape_id'], ['gtfs_shapes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_trips_feed_id'), 'gtfs_trips', ['feed_id'], unique=False)
    op.create_index(op.f('ix_gtfs_trips_id'), 'gtfs_trips', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_trips_route_id'), 'gtfs_trips', ['route_id'], unique=False)
    op.create_index(op.f('ix_gtfs_trips_service_id'), 'gtfs_trips', ['service_id'], unique=False)
    op.create_index(op.f('ix_gtfs_trips_trip_id'), 'gtfs_trips', ['trip_id'], unique=False)
    op.create_table('gtfs_stop_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(length=8), nullable=False, comment='Format: HH:MM:SS'),
    sa.Column('departure_time', sa.String(length=8), nullable=False, comment='Format: HH:MM:SS'),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_headsign', sa.String(length=255), nullable=True),
    sa.Column('pickup_type', sa.Integer(), nullable=True, comment='0=regular, 1=none, 2=phone, 3=driver'),
    sa.Column('drop_off_type', sa.Integer(), nullable=True, comment='0=regular, 1=none, 2=phone, 3=driver'),
    sa.Column('shape_dist_traveled', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('timepoint', sa.Integer(), nullable=True, comment='0=approximate, 1=exact'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['gtfs_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['gtfs_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_stop_times_id'), 'gtfs_stop_times', ['id'], unique=False)
    op.create_index(op.f('ix_gtfs_stop_times_stop_id'), 'gtfs_stop_times', ['stop_id'], unique=False)
    op.create_index(op.f('ix_gtfs_stop_times_trip_id'), 'gtfs_stop_times', ['trip_id'], unique=False)
    # Note: layer, topology, and spatial_ref_sys are PostGIS system tables - do not drop
    op.alter_column('agencies', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-friendly identifier',
               existing_nullable=False)
    op.alter_column('async_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Celery task ID',
               existing_nullable=False)
    op.alter_column('async_tasks', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Progress percentage (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('async_tasks', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Input parameters',
               existing_nullable=True)
    op.alter_column('async_tasks', 'result_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Result data',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=postgresql.ENUM('create', 'update', 'delete', 'import', 'export', 'login', 'logout', name='auditaction'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment="e.g., 'route', 'stop', 'trip'",
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID of the entity that was changed',
               existing_nullable=False)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Previous values (for updates/deletes)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='New values (for creates/updates)',
               existing_nullable=True)
    op.alter_column('user_agencies', 'role',
               existing_type=postgresql.ENUM('super_admin', 'agency_admin', 'editor', 'viewer', name='userrole'),
               comment='User role for this agency',
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_agencies', 'role',
               existing_type=postgresql.ENUM('super_admin', 'agency_admin', 'editor', 'viewer', name='userrole'),
               comment=None,
               existing_comment='User role for this agency',
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::userrole"))
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='New values (for creates/updates)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Previous values (for updates/deletes)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID of the entity that was changed',
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="e.g., 'route', 'stop', 'trip'",
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('create', 'update', 'delete', 'import', 'export', 'login', 'logout', name='auditaction'),
               existing_nullable=False)
    op.alter_column('async_tasks', 'result_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Result data',
               existing_nullable=True)
    op.alter_column('async_tasks', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Input parameters',
               existing_nullable=True)
    op.alter_column('async_tasks', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Progress percentage (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('async_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Celery task ID',
               existing_nullable=False)
    op.alter_column('agencies', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='URL-friendly identifier',
               existing_nullable=False)
    # Note: spatial_ref_sys, topology, and layer are PostGIS system tables - do not recreate
    op.drop_index(op.f('ix_gtfs_stop_times_trip_id'), table_name='gtfs_stop_times')
    op.drop_index(op.f('ix_gtfs_stop_times_stop_id'), table_name='gtfs_stop_times')
    op.drop_index(op.f('ix_gtfs_stop_times_id'), table_name='gtfs_stop_times')
    op.drop_table('gtfs_stop_times')
    op.drop_index(op.f('ix_gtfs_trips_trip_id'), table_name='gtfs_trips')
    op.drop_index(op.f('ix_gtfs_trips_service_id'), table_name='gtfs_trips')
    op.drop_index(op.f('ix_gtfs_trips_route_id'), table_name='gtfs_trips')
    op.drop_index(op.f('ix_gtfs_trips_id'), table_name='gtfs_trips')
    op.drop_index(op.f('ix_gtfs_trips_feed_id'), table_name='gtfs_trips')
    op.drop_table('gtfs_trips')
    op.drop_index(op.f('ix_gtfs_calendar_dates_service_id'), table_name='gtfs_calendar_dates')
    op.drop_index(op.f('ix_gtfs_calendar_dates_id'), table_name='gtfs_calendar_dates')
    op.drop_table('gtfs_calendar_dates')
    op.drop_index(op.f('ix_gtfs_stops_stop_name'), table_name='gtfs_stops')
    op.drop_index(op.f('ix_gtfs_stops_stop_id'), table_name='gtfs_stops')
    op.drop_index(op.f('ix_gtfs_stops_id'), table_name='gtfs_stops')
    op.drop_index(op.f('ix_gtfs_stops_feed_id'), table_name='gtfs_stops')
    op.drop_index('idx_gtfs_stops_geom', table_name='gtfs_stops', postgresql_using='gist')
    op.drop_table('gtfs_stops')
    op.drop_index(op.f('ix_gtfs_shapes_shape_id'), table_name='gtfs_shapes')
    op.drop_index(op.f('ix_gtfs_shapes_id'), table_name='gtfs_shapes')
    op.drop_index(op.f('ix_gtfs_shapes_feed_id'), table_name='gtfs_shapes')
    op.drop_index('idx_gtfs_shapes_geom', table_name='gtfs_shapes', postgresql_using='gist')
    op.drop_table('gtfs_shapes')
    op.drop_index(op.f('ix_gtfs_routes_route_short_name'), table_name='gtfs_routes')
    op.drop_index(op.f('ix_gtfs_routes_route_id'), table_name='gtfs_routes')
    op.drop_index(op.f('ix_gtfs_routes_id'), table_name='gtfs_routes')
    op.drop_index(op.f('ix_gtfs_routes_feed_id'), table_name='gtfs_routes')
    op.drop_table('gtfs_routes')
    op.drop_index(op.f('ix_gtfs_calendar_service_id'), table_name='gtfs_calendar')
    op.drop_index(op.f('ix_gtfs_calendar_id'), table_name='gtfs_calendar')
    op.drop_index(op.f('ix_gtfs_calendar_feed_id'), table_name='gtfs_calendar')
    op.drop_table('gtfs_calendar')
    op.drop_index(op.f('ix_gtfs_agencies_id'), table_name='gtfs_agencies')
    op.drop_index(op.f('ix_gtfs_agencies_feed_id'), table_name='gtfs_agencies')
    op.drop_table('gtfs_agencies')
    op.drop_index(op.f('ix_gtfs_feeds_imported_by'), table_name='gtfs_feeds')
    op.drop_index(op.f('ix_gtfs_feeds_id'), table_name='gtfs_feeds')
    op.drop_index(op.f('ix_gtfs_feeds_agency_id'), table_name='gtfs_feeds')
    op.drop_table('gtfs_feeds')
    # ### end Alembic commands ###
