"""Add FareAttribute and FeedInfo models

Revision ID: 9b720939e61c
Revises: 0bffc0250cd8
Create Date: 2025-11-25 05:46:00.185974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b720939e61c'
down_revision: Union[str, None] = '0bffc0250cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtfs_fare_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('fare_id', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_type', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('payment_method', sa.Integer(), nullable=False, comment='0=on board, 1=before boarding'),
    sa.Column('transfers', sa.Integer(), nullable=True, comment='0=no, 1=once, 2=twice, empty=unlimited'),
    sa.Column('agency_id', sa.String(length=255), nullable=True),
    sa.Column('transfer_duration', sa.Integer(), nullable=True, comment='Length of time in seconds before a transfer expires'),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Custom/extension fields from GTFS'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_fare_attributes_fare_id'), 'gtfs_fare_attributes', ['fare_id'], unique=False)
    op.create_index(op.f('ix_gtfs_fare_attributes_feed_id'), 'gtfs_fare_attributes', ['feed_id'], unique=False)
    op.create_index(op.f('ix_gtfs_fare_attributes_id'), 'gtfs_fare_attributes', ['id'], unique=False)
    op.create_table('gtfs_feed_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('feed_publisher_name', sa.String(length=255), nullable=False),
    sa.Column('feed_publisher_url', sa.String(length=500), nullable=False),
    sa.Column('feed_lang', sa.String(length=10), nullable=False, comment='ISO 639-1 language code'),
    sa.Column('default_lang', sa.String(length=10), nullable=True, comment='ISO 639-1 language code'),
    sa.Column('feed_start_date', sa.String(length=8), nullable=True, comment='YYYYMMDD'),
    sa.Column('feed_end_date', sa.String(length=8), nullable=True, comment='YYYYMMDD'),
    sa.Column('feed_version', sa.String(length=50), nullable=True),
    sa.Column('feed_contact_email', sa.String(length=255), nullable=True),
    sa.Column('feed_contact_url', sa.String(length=500), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Custom/extension fields from GTFS'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['gtfs_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_feed_info_feed_id'), 'gtfs_feed_info', ['feed_id'], unique=True)
    op.create_index(op.f('ix_gtfs_feed_info_id'), 'gtfs_feed_info', ['id'], unique=False)
    # Removed PostGIS topology table drops - these are system tables
    op.alter_column('agencies', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-friendly identifier',
               existing_nullable=False)
    op.alter_column('async_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Celery task ID',
               existing_nullable=False)
    op.alter_column('async_tasks', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Progress percentage (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('async_tasks', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Input parameters',
               existing_nullable=True)
    op.alter_column('async_tasks', 'result_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Result data',
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment="e.g., 'route', 'stop', 'trip'",
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID of the entity that was changed',
               existing_nullable=False)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Previous values (for updates/deletes)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='New values (for creates/updates)',
               existing_nullable=True)
    op.alter_column('user_agencies', 'role',
               existing_type=postgresql.ENUM('super_admin', 'agency_admin', 'editor', 'viewer', name='userrole'),
               comment='User role for this agency',
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_agencies', 'role',
               existing_type=postgresql.ENUM('super_admin', 'agency_admin', 'editor', 'viewer', name='userrole'),
               comment=None,
               existing_comment='User role for this agency',
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::userrole"))
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='New values (for creates/updates)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Previous values (for updates/deletes)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID of the entity that was changed',
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="e.g., 'route', 'stop', 'trip'",
               existing_nullable=False)
    op.alter_column('async_tasks', 'result_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Result data',
               existing_nullable=True)
    op.alter_column('async_tasks', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Input parameters',
               existing_nullable=True)
    op.alter_column('async_tasks', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Progress percentage (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('async_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Celery task ID',
               existing_nullable=False)
    op.alter_column('agencies', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='URL-friendly identifier',
               existing_nullable=False)
    # Removed PostGIS topology table recreations - these are system tables
    op.drop_index(op.f('ix_gtfs_feed_info_id'), table_name='gtfs_feed_info')
    op.drop_index(op.f('ix_gtfs_feed_info_feed_id'), table_name='gtfs_feed_info')
    op.drop_table('gtfs_feed_info')
    op.drop_index(op.f('ix_gtfs_fare_attributes_id'), table_name='gtfs_fare_attributes')
    op.drop_index(op.f('ix_gtfs_fare_attributes_feed_id'), table_name='gtfs_fare_attributes')
    op.drop_index(op.f('ix_gtfs_fare_attributes_fare_id'), table_name='gtfs_fare_attributes')
    op.drop_table('gtfs_fare_attributes')
    # ### end Alembic commands ###
