"""add_external_feed_sources

Revision ID: fa0f147f32eb
Revises: 5d7791b0b787
Create Date: 2025-11-27 07:17:14.628182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0f147f32eb'
down_revision: Union[str, None] = '5d7791b0b787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_feed_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name for this feed source'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description'),
    sa.Column('source_type', sa.Enum('gtfs_static', 'gtfs_realtime', name='feedsourcetype'), nullable=False, comment='Type of GTFS feed'),
    sa.Column('url', sa.String(length=2000), nullable=False, comment='URL to the GTFS feed (zip or realtime)'),
    sa.Column('auth_type', sa.String(length=50), nullable=True, comment='Authentication type: none, api_key, basic, bearer'),
    sa.Column('auth_header', sa.String(length=100), nullable=True, comment='Header name for API key auth'),
    sa.Column('auth_value', sa.String(length=500), nullable=True, comment='Auth value (encrypted in production)'),
    sa.Column('check_frequency', sa.Enum('hourly', 'daily', 'weekly', 'manual', name='checkfrequency'), nullable=False, comment='How often to check for updates'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='Whether monitoring is enabled'),
    sa.Column('auto_import', sa.Boolean(), nullable=False, comment='Automatically import when changes detected'),
    sa.Column('status', sa.Enum('active', 'paused', 'error', 'pending', name='feedsourcestatus'), nullable=False, comment='Current status'),
    sa.Column('last_checked_at', sa.String(length=100), nullable=True, comment='When the source was last checked'),
    sa.Column('last_successful_check', sa.String(length=100), nullable=True, comment='When the source was last successfully checked'),
    sa.Column('last_import_at', sa.String(length=100), nullable=True, comment='When data was last imported'),
    sa.Column('last_etag', sa.String(length=500), nullable=True, comment='ETag from last check for change detection'),
    sa.Column('last_modified', sa.String(length=100), nullable=True, comment='Last-Modified header from last check'),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True, comment='SHA256 hash of last downloaded content'),
    sa.Column('error_count', sa.Integer(), nullable=False, comment='Consecutive error count'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('import_options', sa.JSON(), nullable=True, comment='Import options (skip_shapes, validate_only, etc.)'),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('created_feed_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_feed_id'], ['gtfs_feeds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_feed_sources_agency_id'), 'external_feed_sources', ['agency_id'], unique=False)
    op.create_index(op.f('ix_external_feed_sources_id'), 'external_feed_sources', ['id'], unique=False)
    op.create_table('feed_source_check_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_source_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.String(length=100), nullable=False, comment='When the check occurred'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the check was successful'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='HTTP status code'),
    sa.Column('content_changed', sa.Boolean(), nullable=False, comment='Whether content changed'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA256 hash of content'),
    sa.Column('content_size', sa.Integer(), nullable=True, comment='Size of downloaded content in bytes'),
    sa.Column('import_triggered', sa.Boolean(), nullable=False, comment='Whether import was triggered'),
    sa.Column('import_task_id', sa.String(length=255), nullable=True, comment='Celery task ID if import was triggered'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if check failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['external_feed_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_source_check_logs_feed_source_id'), 'feed_source_check_logs', ['feed_source_id'], unique=False)
    op.create_index(op.f('ix_feed_source_check_logs_id'), 'feed_source_check_logs', ['id'], unique=False)
    # Note: Removed auto-generated drop_table for PostGIS system tables (layer, topology, spatial_ref_sys)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed auto-generated create_table for PostGIS system tables
    op.drop_index(op.f('ix_feed_source_check_logs_id'), table_name='feed_source_check_logs')
    op.drop_index(op.f('ix_feed_source_check_logs_feed_source_id'), table_name='feed_source_check_logs')
    op.drop_table('feed_source_check_logs')
    op.drop_index(op.f('ix_external_feed_sources_id'), table_name='external_feed_sources')
    op.drop_index(op.f('ix_external_feed_sources_agency_id'), table_name='external_feed_sources')
    op.drop_table('external_feed_sources')
    # ### end Alembic commands ###
