"""Add AgencyValidationPreferences model

Revision ID: 66d152b34e85
Revises: 9b720939e61c
Create Date: 2025-11-25 06:00:38.746444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66d152b34e85'
down_revision: Union[str, None] = '9b720939e61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_validation_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False, comment='One preferences record per agency'),
    sa.Column('validate_route_agency', sa.Boolean(), nullable=False, comment='Validate route without valid agency'),
    sa.Column('validate_route_duplicates', sa.Boolean(), nullable=False, comment='Validate duplicated route_id'),
    sa.Column('validate_route_mandatory', sa.Boolean(), nullable=False, comment='Validate route mandatory fields'),
    sa.Column('validate_shape_dist_traveled', sa.Boolean(), nullable=False, comment='Validate shape_dist_traveled are filled'),
    sa.Column('validate_shape_dist_accuracy', sa.Boolean(), nullable=False, comment='Validate shape_dist_traveled makes sense considering lat/long'),
    sa.Column('validate_shape_sequence', sa.Boolean(), nullable=False, comment='Validate shape_pt_sequence is filled and makes sense'),
    sa.Column('validate_shape_mandatory', sa.Boolean(), nullable=False, comment='Validate shape mandatory fields'),
    sa.Column('validate_calendar_mandatory', sa.Boolean(), nullable=False, comment='Validate calendar mandatory fields'),
    sa.Column('validate_calendar_date_mandatory', sa.Boolean(), nullable=False, comment='Validate calendar_dates mandatory fields'),
    sa.Column('validate_fare_attribute_mandatory', sa.Boolean(), nullable=False, comment='Validate fare_attributes mandatory fields'),
    sa.Column('validate_feed_info_mandatory', sa.Boolean(), nullable=False, comment='Validate feed_info mandatory fields'),
    sa.Column('validate_stop_duplicates', sa.Boolean(), nullable=False, comment='Validate stop_id is not duplicated'),
    sa.Column('validate_stop_mandatory', sa.Boolean(), nullable=False, comment='Validate stop mandatory fields'),
    sa.Column('validate_trip_service', sa.Boolean(), nullable=False, comment='Validate service_id is declared on calendar or calendar_dates'),
    sa.Column('validate_trip_duplicates', sa.Boolean(), nullable=False, comment='Validate trip_id is unique'),
    sa.Column('validate_trip_shape', sa.Boolean(), nullable=False, comment='Validate shape_id is a valid shape'),
    sa.Column('validate_trip_mandatory', sa.Boolean(), nullable=False, comment='Validate trip mandatory fields'),
    sa.Column('validate_stop_time_trip', sa.Boolean(), nullable=False, comment='Validate trip_id is valid and in trips list'),
    sa.Column('validate_stop_time_stop', sa.Boolean(), nullable=False, comment='Validate stop_id is valid'),
    sa.Column('validate_stop_time_sequence', sa.Boolean(), nullable=False, comment='Validate stop_sequence makes sense'),
    sa.Column('validate_stop_time_mandatory', sa.Boolean(), nullable=False, comment='Validate stop_time mandatory fields'),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional custom validation settings'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_validation_preferences_agency_id'), 'agency_validation_preferences', ['agency_id'], unique=True)
    op.create_index(op.f('ix_agency_validation_preferences_id'), 'agency_validation_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agency_validation_preferences_id'), table_name='agency_validation_preferences')
    op.drop_index(op.f('ix_agency_validation_preferences_agency_id'), table_name='agency_validation_preferences')
    op.drop_table('agency_validation_preferences')
    # ### end Alembic commands ###
